# probar_historia.py
# Valida guardar_en_historia EN AISLAMIENTO antes de tocar agent.py.
# Prueba lo unico que de verdad importa: que lo que escribimos se pueda
# recuperar despues (que el embedding de escritura case con el de lectura).

import os
import chromadb
from tools import guardar_en_historia, marcar_como_procesado

print("=" * 60)
print("PRUEBA 1 — guardar_en_historia (escritura)")
print("=" * 60)

reporte_prueba = """PROJECT INTELLIGENCE REPORT
============================
PROJECT: CVS #4471 (TEST)
LOCATION: Dallas, TX
CLIENT: CVS
DATE: 2026-06-29
CURRENT STATUS: ATTENTION — drywall 80% complete, day 6 on site.
ISSUES DETECTED: minor delay risk; crew on site 6 consecutive days.
RISK LEVEL: MEDIUM
---
Generated by JRS Central Operations Intelligence System (TEST)
"""

res = guardar_en_historia(
    report_text=reporte_prueba,
    doc_type="crew_update",
    date="2026-06-29",
    risk_level="MEDIUM",
    clients="CVS, Target",
    projects="CVS #4471, Target #1820",
    source_email_id="TEST-0001",
)
print("Resultado:", res)

print()
print("=" * 60)
print("PRUEBA 2 — recuperar por query semantica (lectura)")
print("=" * 60)
print("Si el embedding caso, 'crew_update_TEST-0001' debe volver con")
print("distancia baja (< 1.0) ante una query relacionada.\n")

cliente = chromadb.PersistentClient(path=os.getenv("CHROMA_DB_PATH", "./chroma_data"))
col = cliente.get_or_create_collection("collection_jrs_history")
q = col.query(query_texts=["CVS drywall progress crew delay"], n_results=3)

ids = q.get("ids", [[]])[0]
dists = q.get("distances", [[]])[0]
for i, d in zip(ids, dists):
    marca = "  <-- nuestro doc de prueba" if i == "crew_update_TEST-0001" else ""
    print(f"  id={i:35s} distancia={d:.4f}{marca}")

print()
if "crew_update_TEST-0001" in ids:
    print("RESULTADO: OK — el documento se guardo Y se recupero. Embedding consistente.")
else:
    print("RESULTADO: REVISAR — el doc no volvio en la query. Posible mismatch de embedding.")

print()
print("=" * 60)
print("LIMPIEZA opcional — borrar el doc de prueba")
print("=" * 60)
col.delete(ids=["crew_update_TEST-0001"])
print("Doc de prueba borrado. Total ahora:", col.count())

print()
print("NOTA: marcar_como_procesado NO se prueba aqui porque necesita un")
print("email_id real con la etiqueta AI-Agent. Se valida en el flujo vivo")
print("cuando integremos agent.py (el correo debe pasar de AI-Agent a AI-Procesado).")
